export {
  switchLight,
  switchOffAllLights,
  listAllLights,
  getLightsByRoom,
  findLightByName,
  switchLightByName,
  setLightBrightness,
  setLightBrightnessByName,
  setLightColorTemperature,
  setLightColorTemperatureByName,
  setLightColor,
  setLightColorByName,
  getLightInfo,
  getLightInfoByName,
  initializeLightCache,
  refreshLightCache,
  getCachedLights,
  getCacheStatus
} from './api.js';
